export enum TipoProducto {
  REFRIGERADO = 'REFRIGERADO',
  ALIMENTO = 'ALIMENTO',
  LIMPIEZA = 'LIMPIEZA',
  ELECTRODOMESTICOS = 'ELECTRODOMESTICOS',
  PERECEDEROS = 'PERECEDEROS',
  OTROS = 'OTROS',
}
